name: Publish Helm Chart

on:
  push:
    tags:
      - 'v*'  # реагирует на все теги вида vX.Y.Z или vX.Y.Z-rc1

jobs:
  build-and-publish:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.14.0

      - name: Package Helm chart
        run: |          
          VERSION=$(grep '^version:' Chart.yaml | awk '{print $2}')
          helm package . --version $VERSION --destination ./charts

      - name: Update Helm repo index
        run: |
          helm repo index ./charts --url https://rayderua.github.io/argocd-ingress-chart/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./charts
          publish_branch: gh-pages
